spring:
  proxyee:
    host: 127.0.0.1
    port: 9999
    upstream:
      host: 127.0.0.1
      port: 7890
    ssl:
      caCert: classpath*:ca.crt
      caKey: classpath*:ca_private.der
      chicpers:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_128_CBC_SHA
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    threads:
      work: 3
      proxy: 0
      boss: 5
    auth:
      username: test
      password: 123