spring:
  proxyee:
    host: 127.0.0.1
    port: 9999
    upstream:
      host: 127.0.0.1
      port: 7890
    ssl:
      caCert: classpath*:ca.crt
      caKey: classpath*:ca_private.der
    threads:
      work: 3
      proxy: 4
      boss: 5
    auth:
      username: test
      password: 123